# String for model factory
model_str: "mast3r"
# Model config
model_config:
  name: "mast3r"
  # Checkpoint path
  ckpt_path: "${root_pretrained_checkpoints_dir}/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth"
  # Cache dir
  cache_dir: "${root_pretrained_checkpoints_dir}/mast3r_cache"
  # is share intrinsics
  sparse_ga_shared_intrinsics: true
# Image Normalization Type
data_norm_type: "dust3r"
# MASt3R checkpoint is already loaded in the inference wrapper
pretrained: null
# Torch hub force reload
torch_hub_force_reload: false
# test resolution
test_resolution: [512, 336]
postprocessing:
  isAffineRefineDepthWithInputDepth: true
  isConsistencyCheck: false
  isJustCompareNearDistance: false
  maximum_near_distance: 10 # unit metter